Repository INU-BJJ/bjj-server, pull requests merged in 2025-03, with the labels that each got.

#57 [Feat/#49] 마이페이지 관련 api 추가 & 아이템 착용 api 추가
  src/main/java/com/appcenter/BJJ/domain/item/controller/ItemController.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Inventory.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/MyItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/InventoryRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/ItemRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemService.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberService.java
  src/main/java/com/appcenter/BJJ/domain/member/domain/Member.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorCode.java
  src/main/java/com/appcenter/BJJ/global/jwt/JwtFilter.java
  src/main/java/com/appcenter/BJJ/global/oauth/OAuth2UserServiceExt.java
Labels: ✨feat, 🔨refactor

#62 [Feat/#61] test용 회원의 포인트 추가 & 마이페에지 response 필드값 설정 수정
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemService.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberController.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberService.java
  src/main/java/com/appcenter/BJJ/domain/member/dto/PointRes.java
Labels: ✨feat, 🔨refactor

#65 [Fix/#64] 스웨거 description이 비정상적으로 출력되는 문제 해결
  src/main/java/com/appcenter/BJJ/domain/menu/controller/TodayDietController.java
  src/main/java/com/appcenter/BJJ/domain/review/controller/ReviewController.java
Labels: 🚑fix

#66 [Refactor/#63] 마이페이지에서 캐릭터와 배경에 대한 정보 response에 담기 & 아이템 api를 itemType으로 구별하기
  src/main/java/com/appcenter/BJJ/domain/item/controller/ItemController.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Inventory.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Item.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/DetailItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/ItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/ItemVO.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/MyItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/enums/ItemLevel.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/InventoryRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/ItemRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemManagementService.java
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemService.java
Labels: 🔨refactor

#69 [Feat/#68] 리뷰에서 식단과 일치하는 메뉴의 비교가 가능하도록 반환 값에 주 메뉴 및 부 메뉴 id 추가
  src/main/java/com/appcenter/BJJ/domain/review/dto/ReviewDetailRes.java
  src/main/java/com/appcenter/BJJ/domain/review/repository/ReviewRepository.java
  src/main/java/com/appcenter/BJJ/domain/review/repository/ReviewRepositoryImpl.java
Labels: ✨feat
