Repository INU-BJJ/bjj-server, pull requests merged in 2025-02, with the labels that each got.

#42 [Feat/#36] 이미지 조회 방식 변경에 따른 이미지 조회 API 수정
  src/main/java/com/appcenter/BJJ/domain/image/ImageController.java
Labels: ✨feat

#37 [Feat/#25] 아이템 저장 및 뽑기 서비스 추가
  src/main/java/com/appcenter/BJJ/domain/item/controller/InventoryController.java
  src/main/java/com/appcenter/BJJ/domain/item/controller/ItemController.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Inventory.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Item.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/GachaRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/ItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/ItemVO.java
  src/main/java/com/appcenter/BJJ/domain/item/enums/ItemLevel.java
  src/main/java/com/appcenter/BJJ/domain/item/enums/ItemType.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/InventoryRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/ItemRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/service/InventoryService.java
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemService.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberController.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberRepository.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberRole.java
  src/main/java/com/appcenter/BJJ/domain/member/MemberService.java
  src/main/java/com/appcenter/BJJ/domain/member/domain/Item.java
  src/main/java/com/appcenter/BJJ/domain/member/domain/Member.java
  src/main/java/com/appcenter/BJJ/domain/member/dto/MemberOAuthVO.java
  src/main/java/com/appcenter/BJJ/global/config/WebMvcConfig.java
  src/main/java/com/appcenter/BJJ/global/exception/CustomException.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorCode.java
  src/main/java/com/appcenter/BJJ/global/jwt/UserDetailsImpl.java
  src/main/java/com/appcenter/BJJ/global/jwt/UserDetailsServiceImpl.java
  src/main/java/com/appcenter/BJJ/global/oauth/OAuth2SuccessHandler.java
  src/main/java/com/appcenter/BJJ/global/oauth/OAuth2UserServiceExt.java
Labels: ✨feat, 🔨refactor, 🎨style, 🚀chore

#45 [Refactor/#40] error 관련 코드 전체적으로 수정
  src/main/java/com/appcenter/BJJ/domain/member/MemberService.java
  src/main/java/com/appcenter/BJJ/global/exception/CustomExceptionHandler.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorCode.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorDTO.java
  src/main/java/com/appcenter/BJJ/global/jwt/AccessDeniedHandlerImpl.java
  src/main/java/com/appcenter/BJJ/global/jwt/AuthenticationEntryPointImpl.java
  src/main/java/com/appcenter/BJJ/global/jwt/JwtValidateFilter.java
Labels: 🔨refactor

#47 [Feat/#38] 아이템 뽑기 관련 기능 추가 & inventory 아이템 조회 기능
  src/main/java/com/appcenter/BJJ/domain/item/controller/InventoryController.java
  src/main/java/com/appcenter/BJJ/domain/item/controller/ItemController.java
  src/main/java/com/appcenter/BJJ/domain/item/controller/ItemManagementController.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Inventory.java
  src/main/java/com/appcenter/BJJ/domain/item/domain/Item.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/DetailItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/GachaRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/ItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/ItemVO.java
  src/main/java/com/appcenter/BJJ/domain/item/dto/MyItemRes.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/InventoryRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/repository/ItemRepository.java
  src/main/java/com/appcenter/BJJ/domain/item/service/InventoryService.java
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemManagementService.java
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemService.java
Labels: ✨feat, 🔨refactor, 🎨style

#50 [Feat/#46] 식당 정보 조회 추가
  src/main/java/com/appcenter/BJJ/domain/menu/controller/CafeteriaController.java
  src/main/java/com/appcenter/BJJ/domain/menu/dto/CafeteriaInfoRes.java
  src/main/java/com/appcenter/BJJ/domain/menu/repository/CafeteriaRepository.java
  src/main/java/com/appcenter/BJJ/domain/menu/service/CafeteriaService.java
  src/main/java/com/appcenter/BJJ/global/config/WebMvcConfig.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorCode.java
Labels: ✨feat

#53 [Fix] 아이템 저장 경로를 소문자로 변경 #52
  src/main/java/com/appcenter/BJJ/domain/item/service/ItemManagementService.java
Labels: 🚑fix
