Repository INU-BJJ/bjj-server, pull requests merged in 2025-09, with the labels that each got.

#108 [Feat/#105] 회원의 밴처리 추가
  src/main/java/com/appcenter/BJJ/domain/member/enums/MemberStatus.java
  src/main/java/com/appcenter/BJJ/domain/member/schedule/MemberTaskRepository.java
  src/main/java/com/appcenter/BJJ/domain/member/schedule/MemberTaskService.java
  src/main/java/com/appcenter/BJJ/domain/review/service/ReviewReportService.java
  src/main/java/com/appcenter/BJJ/global/config/SecurityConfig.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorCode.java
  src/main/java/com/appcenter/BJJ/global/jwt/JwtFilter.java
  src/main/java/com/appcenter/BJJ/global/jwt/JwtProvider.java
  src/main/java/com/appcenter/BJJ/global/jwt/UserDetailsServiceImpl.java
Labels: ✨feat

#115 [Fix/#87] 메뉴 랭킹 오류 수정
  src/main/java/com/appcenter/BJJ/domain/image/ImageRepository.java
  src/main/java/com/appcenter/BJJ/domain/review/repository/ReviewRepository.java
Labels: 🚑fix

#116 [Feat/#111] 웰컴포인트 지급 이벤트 뷰 추가
  src/main/java/com/appcenter/BJJ/domain/event/Event.java
  src/main/java/com/appcenter/BJJ/domain/event/EventController.java
  src/main/java/com/appcenter/BJJ/domain/event/EventRepository.java
  src/main/java/com/appcenter/BJJ/domain/event/EventService.java
  src/main/java/com/appcenter/BJJ/domain/event/EventType.java
  src/main/resources/static/css/welcome-point.css
  src/main/resources/static/images/banners/welcome-point/background.svg
  src/main/resources/static/images/banners/welcome-point/button.svg
  src/main/resources/static/images/banners/welcome-point/fail_alert.svg
  src/main/resources/static/images/banners/welcome-point/main.svg
  src/main/resources/static/images/banners/welcome-point/success_alert.jpeg
  src/main/resources/templates/banners/welcome-point.html
Labels: ✨feat

#118 [Refactor/#117] 웰컴포인트 참여 API 명세서 수정
  src/main/java/com/appcenter/BJJ/domain/event/EventController.java
Labels: 🔨refactor

#114 [Feat/#110] 배너 관리 및 목록 조회 기능 추가
  src/main/java/com/appcenter/BJJ/domain/banner/Banner.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerController.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerManagementController.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerManagementService.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerRepository.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerReq.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerRes.java
  src/main/java/com/appcenter/BJJ/domain/banner/BannerService.java
  src/main/java/com/appcenter/BJJ/global/config/WebMvcConfig.java
  src/main/java/com/appcenter/BJJ/global/exception/ErrorCode.java
Labels: ✨feat

#122 [Fix/#121] 배너 페이지 화면 스타일 수정
  src/main/resources/static/css/best-review.css
  src/main/resources/static/css/welcome-point.css
  src/main/resources/templates/banners/best-review.html
Labels: 🚑fix

#126 [Refactor/#125] AuthenticationEntryPoint 및 AccessDeniedHandler 에서 발생하는 예외를 스택 형식으로 log 띄우기
  src/main/java/com/appcenter/BJJ/global/jwt/AccessDeniedHandlerImpl.java
  src/main/java/com/appcenter/BJJ/global/jwt/AuthenticationEntryPointImpl.java
Labels: 🔨refactor
